name: Bandit Check

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: 'Working directory to run bandit checks on'
        

jobs:
  bandit:
    name: Run Bandit Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run bandit checks
        run: |
          bandit -r  ${{ github.workspace }}/${{ inputs.working-directory }}
