name: Esims Router CI

on:
  workflow_dispatch:
  push:
    paths:
      - lib/**
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths:
      - lib/**

jobs:
  run-black:
    name: Run Black Checks
    uses: ./.github/workflows/check-black.yml
    with:
      working-directory: lib

  run-pylint:
    name: Run Pylint Checks
    uses: ./.github/workflows/check-pylint.yml
    with:
      working-directory: lib

  run-bandit:
    name: Run Bandit Checks
    uses: ./.github/workflows/check-bandit.yml
    with:
      working-directory: lib

  run-mypy:
    name: Run MyPy Checks
    uses: ./.github/workflows/check-mypy.yml
    with:
      working-directory: lib
      code-directory: esimslib
