name: Refresh Dropbox Deploy Prod

on:
  push:
    paths:
      - refreshdropbox/**
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  set-env:
    name: Set Environment Variables
    uses: ./.github/workflows/env-refreshdropbox.yml
    with:
      stage: prod

  prod-deploy:
    name: Deploy Refresh Dropbox to Prod
    needs: set-env
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      stage: prod
      directory: refreshdropbox
      aws_region: ${{ needs.set-env.outputs.aws_region }}
      image_name: ${{ needs.set-env.outputs.image_name }}
      resource_name: ${{ needs.set-env.outputs.resource_name }}
      image_tag: ${{ github.run_number }}
    secrets: inherit
